/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import controle.ContatoCTL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import modelos.Contato;
import javax.swing.table.DefaultTableModel;
//import modelos.IcrudContato;
import modelos.*;
import controle.ContatoCTL;

/**
 *
 * @author eugen
 */
public class TelaPrincipal extends javax.swing.JFrame {
    //Atributo da Controle
    IcrudContato objContatoCTL = new ContatoCTL();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
      initComponents();
      this.setLocationRelativeTo(null);
      try {
        mostrarListaDeContatos();
      } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro.getMessage());
      }
    }
    private void mostrarListaDeContatos() throws Exception{
      try {
        ArrayList<Contato> listaDeContatos = objContatoCTL.listagemDeContatos();
        DefaultTableModel model =  (DefaultTableModel) jTableDadosDosContatos.getModel();
        model.setNumRows(0);
        if(listaDeContatos.isEmpty()) return;
        for(Contato pessoa : listaDeContatos){
          String[] linha = new String[4];
          linha[0] = pessoa.getIdContato() + "";
          linha[1]= pessoa.getNomeCompleto();
          linha[2] = pessoa.getEmail();
          linha[3] = pessoa.getTelefone().toString();
          model.addRow(linha);
        }
      } catch (Exception erro) {
        throw erro;
      }
    }
    // Método auxiliar para converter o texto em objeto Telefone
    private Telefone extrairTelefone(String entrada) throws Exception {
        //Remove tudo que NÃO for número (regex)
        String apenasNumeros = entrada.replaceAll("[^0-9]", "");
    
        // Validação básica de tamanho
        // Mínimo: 2(DDI) + 2(DDD) + 8(Numero) = 12 digitos
        // Máximo: 2(DDI) + 2(DDD) + 9(Numero) = 13 digitos
        if (apenasNumeros.length() < 12 || apenasNumeros.length() > 13) {
            throw new Exception("Telefone inválido! Digite: DDI + DDD + Número\nEx: 5562999998888");
        }

        //Fatiamento (Parsing)
        try {
            // Pega do índice 0 até o 2 (não incluso) -> Primeiros 2 digitos
            int ddi = Integer.parseInt(apenasNumeros.substring(0, 2));
        
            // Pega do índice 2 até o 4 -> Próximos 2 digitos
            int ddd = Integer.parseInt(apenasNumeros.substring(2, 4));
        
            // Pega do índice 4 até o fim -> O resto é o número
            int numero = Integer.parseInt(apenasNumeros.substring(4));
        
            return new Telefone(ddi, ddd, numero);
        
        } catch (NumberFormatException e) {
            throw new Exception("Erro ao processar os números do telefone.");
        }
    }
    
    private void formatarCampoTelefone() {
    String textoAtual = jTextFieldTelefone.getText();
    
    //Remove tudo que não é número
    String apenasNumeros = textoAtual.replaceAll("[^0-9]", "");
    
    //Proteção para não estourar o limite (DDI 2 + DDD 2 + Num 9 = 13 digitos)
    if (apenasNumeros.length() > 13) {
        apenasNumeros = apenasNumeros.substring(0, 13);
    }

    //Monta a máscara dinamicamente
    String textoFormatado = "";
    
    //Adiciona o DDI
    if (apenasNumeros.length() > 0) {
        textoFormatado += "+" + apenasNumeros.substring(0, Math.min(2, apenasNumeros.length()));
    }
    
    //Adiciona o DDD
    if (apenasNumeros.length() > 2) {
        textoFormatado += " (" + apenasNumeros.substring(2, Math.min(4, apenasNumeros.length()));
    }
    
    // Fecha o parentese do DDD
    if (apenasNumeros.length() >= 4) {
        textoFormatado += ") ";
    }
    
    // Adiciona o Número
    if (apenasNumeros.length() > 4) {
        //Se tiver mais de 8 digitos no numero (total > 4+4=8), coloca o hífen
        if (apenasNumeros.length() > 9) { 
             textoFormatado += apenasNumeros.substring(4, 9) + "-" + apenasNumeros.substring(9);
        } else {
             textoFormatado += apenasNumeros.substring(4);
        }
    }

    //Aplica no campo apenas se mudou (evita loops infinitos)
    if (!textoFormatado.equals(textoAtual)) {
        jTextFieldTelefone.setText(textoFormatado);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDosDados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdContato = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jPanelAcoes = new javax.swing.JPanel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosDosContatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE DA AGENDA DE CONTATOS");

        jPanelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGENDA DE CONTATOS");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelDosDados.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("IDENTIFICADOR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("E-MAIL");

        jTextFieldIdContato.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jPanelAcoes.setBackground(new java.awt.Color(102, 102, 102));

        jButtonIncluir.setBackground(new java.awt.Color(255, 255, 0));
        jButtonIncluir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeA_16.png"))); // NOI18N
        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 0));
        jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/excluir16.png"))); // NOI18N
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonConsultar.setBackground(new java.awt.Color(255, 255, 0));
        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/buscar16.png"))); // NOI18N
        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeC_16.png"))); // NOI18N
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar))
                .addGap(29, 29, 29))
        );

        jTextFieldTelefone.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("TELEFONE");

        javax.swing.GroupLayout jPanelDosDadosLayout = new javax.swing.GroupLayout(jPanelDosDados);
        jPanelDosDados.setLayout(jPanelDosDadosLayout);
        jPanelDosDadosLayout.setHorizontalGroup(
            jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdContato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelDosDadosLayout.setVerticalGroup(
            jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDosDadosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTableDadosDosContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "NOME COMPLETO", "E-MAIL", "TELEFONE"
            }
        ));
        jTableDadosDosContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDadosDosContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDadosDosContatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanelDosDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDosDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void limparDadosTela(){
    jTextFieldIdContato.setText("");
    jTextFieldNome.setText("");
    jTextFieldEmail.setText("");
    jTextFieldTelefone.setText("");
    jTextFieldIdContato.setEnabled(true);
  }
  private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
    // TODO add your handling code here:
    try {
      Contato objetoContato = null;
      int idContato = 0;
      try{
          idContato = Integer.parseInt(jTextFieldIdContato.getText());
      } catch (NumberFormatException error){
          throw new Exception("O número ID deve ser inteiro!");
      }
      String nome = jTextFieldNome.getText();
      String email = jTextFieldEmail.getText();
      Telefone fone = extrairTelefone(jTextFieldTelefone.getText());
      objetoContato = new Contato(idContato, nome,email, fone);
      objContatoCTL.incluir(objetoContato);
      limparDadosTela();
      mostrarListaDeContatos();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonIncluirActionPerformed

  private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
    // TODO add your handling code here:
    try{
        if(jTextFieldNome.getText().isEmpty()){
            throw new Exception("Digite um nome para consultar!");
        }
        String nome = jTextFieldNome.getText();
        
        Contato contatoEncontrado = objContatoCTL.consultar(nome);
        
        if(contatoEncontrado == null){
            throw new Exception("Contato com nome: " + nome + ", não encontrado");
        }
        jTextFieldIdContato.setText(String.valueOf(contatoEncontrado.getIdContato()));
        jTextFieldNome.setText(contatoEncontrado.getNomeCompleto());
        jTextFieldEmail.setText(contatoEncontrado.getEmail());
        jTextFieldTelefone.setText(contatoEncontrado.getTelefone().toString());
        
    } catch (NumberFormatException error){
        JOptionPane.showMessageDialog(null, "Digite um nome válido!");
    } catch (Exception error) {
        JOptionPane.showMessageDialog(null, error.getMessage());
    }
    
  }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jTextFieldTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneKeyReleased
        // TODO add your handling code here:
        formatarCampoTelefone();
    }//GEN-LAST:event_jTextFieldTelefoneKeyReleased

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        try{
            if(jTextFieldIdContato.getText().isEmpty()){
                throw new Exception("Digite o ID que deseja excluir");
            }
            int id = Integer.parseInt(jTextFieldIdContato.getText());
            
            // Confirmar decisão
            int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja excluir?");
            if(resposta != JOptionPane.YES_OPTION)return;
            objContatoCTL.excluir(id);
            
            limparDadosTela();
            mostrarListaDeContatos();
            JOptionPane.showMessageDialog(null, "Contato excluído com sucesso!");
            
        } catch (NumberFormatException error){
            JOptionPane.showMessageDialog(null, "O ID deve ser um número inteiro!");
        } catch (Exception error){
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
        int idContato = 0;
        try {
            idContato = Integer.parseInt(jTextFieldIdContato.getText());
        } catch (NumberFormatException e) {
            throw new Exception("Informe o ID que deseja alterar!");
        }
        
        String nome = jTextFieldNome.getText();
        String email = jTextFieldEmail.getText();
        
        Telefone fone = extrairTelefone(jTextFieldTelefone.getText());

        Contato objetoContato = new Contato(idContato, nome, email, fone);
        
        
        // Manda alterar
        objContatoCTL.alterar(objetoContato);
        
        limparDadosTela();
        mostrarListaDeContatos();
        JOptionPane.showMessageDialog(null, "Contato alterado com sucesso!");
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableDadosDosContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDadosDosContatosMouseClicked
        // TODO add your handling code here:
        try{
            int linhaSelecionada = jTableDadosDosContatos.getSelectedRow();
            if(linhaSelecionada == -1)return;
            
            String nome = jTableDadosDosContatos.getValueAt(linhaSelecionada, 1).toString();
            
            jTextFieldNome.setText(nome);
            jButtonConsultarActionPerformed(null);
            jTextFieldIdContato.setEnabled(false);
        } catch (Exception error){
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_jTableDadosDosContatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelDosDados;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosDosContatos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdContato;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
